[package]
name = "timer_wrapper_future"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project = "1.1.0"
rand = "^0.8"
reqwest = "0.11.18"
tokio = { version = "1.28.2", features = ["full"] }
